import { useEffect, useState } from "react"
import "./index.css"

export default function App() {
  const [health, setHealth] = useState<string>("checking...")

  useEffect(() => {
    fetch("/api/health")
      .then(r => r.json())
      .then(d => setHealth(d.status))
      .catch(() => setHealth("backend unreachable"))
  }, [])

  return (
    <div className="min-h-screen bg-gray-50 flex items-center justify-center">
      <div className="bg-white p-8 rounded-lg shadow-md text-center">
        <h1 className="text-3xl font-bold text-cgi mb-4">hello-factory-v3</h1>
        <p className="text-gray-700">Backend status: <span className="font-mono">{health}</span></p>
        <p className="text-sm text-gray-400 mt-4">Generated by CGI Factory</p>
      </div>
    </div>
  )
}